### ISSUE TITLE
动画每次调用start都会闪动

### ISSUE THREAD

**Issue by zsytssk** [svga/SVGAPlayer-Web-Lite#10]
我有一个角色 需要在两个动画间切换， 每次调用start的时候动画都会闪动一下， 衔接不顺畅。
即使已经在播放的动画 每次调用start时候都会闪动下；
我猜测这是每次 start， 都会重新初始化动画， 这会导致闪动...,

有没有可能已经初始化的动画在start的时候不要闪动， 顺滑的播放？

**Comment by lijialiang** [comment]
能否提供一个 demo ？

按现有逻辑，同一个 canvas 做动画衔接，不排除会出现空白帧，或者尝试多 canvas 做动画衔接。
