### ISSUE TITLE
新版本的svga.lite只卡第一帧无法播放（疑似2.0兼容性问题）

### ISSUE THREAD

**Issue by zy445566** [svga/SVGAPlayer-Web-Lite#11]
最小问题实例展示: https://zy445566.github.io/svga/index.html
最小代码仓库地址:https://github.com/zy445566/zy445566.github.io/blob/master/svga/index.html
浏览器版本：Google Chrome 版本 83.0.4103.61（正式版本） （64 位）
导出svga版本是2.0，怀疑是素材兼容性问题，导出工具和官网预览可以播放

**Comment by lijialiang** [comment]
感谢你的反馈，麻烦请尝试一下这个版本 

`https://cdn.jsdelivr.net/npm/svga.lite@1.4.1-beta.1/svga.lite.min.js`

**Comment by zy445566** [comment]
> 感谢你的反馈，麻烦请尝试一下这个版本
> 
> `https://cdn.jsdelivr.net/npm/svga.lite@1.4.1-beta.1/svga.lite.min.js`

这个正常使用了
