### ISSUE TITLE
why not requestAnimationFrame

### ISSUE THREAD

**Issue by windyrain** [svga/SVGAPlayer-Web-Lite#12]
https://github.com/svga/SVGAPlayer-Web-Lite/blob/master/core/player/animator.ts#L11

![image](https://user-images.githubusercontent.com/7961364/91538578-9b440780-e94a-11ea-939f-d98aada2972c.png)

![image](https://user-images.githubusercontent.com/7961364/91538726-d5ada480-e94a-11ea-8168-d538162b452a.png)

**Comment by lijialiang** [comment]
Because we need to support Android 4.0 in the past few years, we will reconsider the support of the browser. We will update as soon as we have a clear answer. Thank you very much for your reply.

**Comment by windyrain** [comment]
Thank you for your prompt reply ！
