### ISSUE TITLE
iPhone7 iOS13.5.1 WKWebview high cpu

### ISSUE THREAD

**Issue by windyrain** [svga/SVGAPlayer-Web-Lite#13]
svga.lite is very nice💗 !
but in iPhone7 iOS13.5.1, it take too high cpu
I try do something below

* `setTimeout -> requestAnimationFrame`
* `bind doFrame in constructor`
*  judge loop by `loop != 1 / 0` before now condition

but not work, I want some help ~

There is a cpu compare picture capture by instruments
* without svga, average 2%
![image](https://user-images.githubusercontent.com/7961364/91628807-10b8e200-e9f6-11ea-9590-e2f40c0faed5.png)

* with svga, average 20% ~ 30%
![image](https://user-images.githubusercontent.com/7961364/91628844-43fb7100-e9f6-11ea-94a7-dc6d859da814.png)

here is my svga file: https://cdn.kaishuhezi.com/kstory/activity_flow/attachment/51f8c9b5-8b04-4d41-a0c6-4f446ddc63e0_info__s=37118.svga

**Comment by lijialiang** [comment]
In personal tests, I found that 20% ~ 30% is a relatively standard performance, even if I simply use canvas drawImage for one frame, I get the same result.

```js
var canvas = document.getElementById('canvas')
canvas.width = 500
canvas.height = 650
var ctx = canvas.getContext('2d')

var image = new Image()
image.src = 'https://iovo-oss.yy.com/upload/1598855714241m7PAtP7hc.png'

function draw () {
  ctx.drawImage(image, 0, 0)
}
setInterval(draw, 16)
```

![image](https://user-images.githubusercontent.com/12247242/91690119-ffa7d680-eb97-11ea-8f8d-f78ff9a307fb.png)

**Comment by windyrain** [comment]
yeah, I found almost all animate lib(lottie, tween) take the same or higher cpu use.
I will replace loop animate with apng.
thank you for your reply, have a nice day ~

**Comment by veeking** [comment]
What is performance tool  with the picture example？

> In personal tests, I found that 20% ~ 30% is a relatively standard performance, even if I simply use canvas drawImage for one frame, I get the same result.
> 
> ```js
> var canvas = document.getElementById('canvas')
> canvas.width = 500
> canvas.height = 650
> var ctx = canvas.getContext('2d')
> 
> var image = new Image()
> image.src = 'https://iovo-oss.yy.com/upload/1598855714241m7PAtP7hc.png'
> 
> function draw () {
>   ctx.drawImage(image, 0, 0)
> }
> setInterval(draw, 16)
> ```
> 
> ![image](https://user-images.githubusercontent.com/12247242/91690119-ffa7d680-eb97-11ea-8f8d-f78ff9a307fb.png)


What is performance tool  with the picture example？
