### ISSUE TITLE
videoEntity img dynamic replace by unknown original?

### ISSUE THREAD

**Issue by windyrain** [svga/SVGAPlayer-Web-Lite#18]
![image](https://user-images.githubusercontent.com/7961364/92870307-45855a00-f436-11ea-810e-117230e8006f.png)
![image](https://user-images.githubusercontent.com/7961364/92870352-5930c080-f436-11ea-812a-779e0085192d.png)

A strange question occur in EML-AL00 HUAWEI p20, at the same time, other phones are normal

I read the code in renderer.ts, img draw by canvas.drawImage, but it has way to draw another img by dynamicElement
![image](https://user-images.githubusercontent.com/7961364/92871764-e0caff00-f437-11ea-8e63-e68a06711211.png)

but I don't do anything about dynamicElement, any investigation methods or solutation.
here is my svga cdn url: https://cdn.kaishuhezi.com/kstory/activity_flow/attachment/591d0c21-4c10-4152-9bb0-760cd962db9b_info__s=8428.svga

**Comment by windyrain** [comment]
I communicate with my android workmate, they doubt this is caused by android canvas cache.

**Comment by windyrain** [comment]
I'am sure this not cause by dynamicElements, It's draw by _bitmapCache.

**Comment by lijialiang** [comment]
If you set dynamic elements through the lite version, the sprite image will be replaced. 

If this problem occurs only on special models, please print out `svgaData.dynamicElements`. You can see if dynamic elements are set.

**Comment by lijialiang** [comment]
Each player in the lite version has an independent _bitmapCache during instantiation, and there should be no cache.

**Comment by windyrain** [comment]
why boss's phone always exist strange question, too helpless.

**Comment by lijialiang** [comment]
I have some suggestions for finding the problem:

1. Check if there is a cache of svga files
2. Check if any dynamic element is called instead of `_bitmapCache[key]`
3. The sprite images in the SVGA file are all in base64 format, check the generated Image object in the console

**Comment by windyrain** [comment]
![image](https://user-images.githubusercontent.com/7961364/93100365-a5505f00-f6db-11ea-8699-dcd2a886ff13.png)

thank you all the same, cdn file has not change in the past 2 weeks,  I think it's a mobile self bug !

**Comment by lijialiang** [comment]
Thank you very much for your feedback. 

If you have other questions, please ask again, and you are welcome to raise a PR for our bug.
