### ISSUE TITLE
Replace WebSQL with IndexedDB

### ISSUE THREAD

**Issue by Naeemo** [svga/SVGAPlayer-Web-Lite#19]
Reasons:
1. The Web SQL Database specification is no longer being maintained and support may be dropped in future versions.
2. Accroding to [caniuse.com](https://caniuse.com/), [IndexedDB](https://caniuse.com/indexeddb) is much better supported than [WebSQL](https://caniuse.com/sql-storage).
3. If necessary, IndexedDB can cover all WebSQL-supported browsers(there is a [polyfill for IndexedDB based on WebSQL](https://github.com/indexeddbshim/IndexedDBShim)).

I can try to provide a PR,  if you guys also agree on this.
😊

**Comment by lijialiang** [comment]
We welcome this very much 👏🏻

**Comment by Naeemo** [comment]
OK, I'll start soon.

https://github.com/Naeemo/SVGAPlayer-Web-Lite/tree/indexeddb

**Comment by lijialiang** [comment]
Here is a [1.5.0-beta.2](https://www.npmjs.com/package/svga.lite/v/1.5.0-beta.2) version. 

Thanks again for your PR :)
