### ISSUE TITLE
[Feature Request] Probably a switch between requestAnimationFrame and setTimeout

### ISSUE THREAD

**Issue by Naeemo** [svga/SVGAPlayer-Web-Lite#22]
> Most browsers stop sending [`requestAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame) callbacks to background tabs or hidden [`<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)s in order to improve performance and battery life.
_from_ [MDN Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#Policies_in_place_to_aid_background_page_performance)

However, there is some use cases we need the svga to keep on playing no matter what. For example, a countdown that has a svga playing as a visual notice, and rely on the svga's completion callback for later work.
Under these scenarios, setTimeout can do the job. Maybe there is anything else as a workround, please let me know.

If the feature seems useful, I can try to provide a PR 😬

**Comment by Naeemo** [comment]
related #12

**Comment by lijialiang** [comment]
For such a situation, setTimeout does not seem to be the best solution :(
because setTimeout will also encounter the problem of delayed function execution.  For example like [this](https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs).

I think it is possible to put the timer on the `webworker` to solve this problem more completely? 🤔

**Comment by Naeemo** [comment]
Thanks for the notice, `webworker` seems right to me too.
Then the switch is between the two options below, am I right?

1. running [`core/player/animator.ts`](https://github.com/svga/SVGAPlayer-Web-Lite/blob/3ad3f5a34f4cf8ff0651a848ac8a696807e51528/core/player/animator.ts) in main thread based on `requestAnimationFrame`
2. running [`core/player/animator.ts`](https://github.com/svga/SVGAPlayer-Web-Lite/blob/3ad3f5a34f4cf8ff0651a848ac8a696807e51528/core/player/animator.ts) in `webworker` based on `setInterval`

----
If so, I also have a name in mind: `noExecutionDelay`
``` typescript
 interface options { 
   loop: number | boolean 
   fillMode: FILL_MODE 
   playMode: PLAY_MODE 
   startFrame: number 
   endFrame: number 
   cacheFrames: boolean 
   intersectionObserverRender: boolean 
   noExecutionDelay: boolean
 } 
```
usage:
``` javascript
const player = new Player('#canvas')

// all events will fire without any delay from browser performance policies.
// web worker will be used
play.set({ noExecutionDelay: true })
```

**Comment by lijialiang** [comment]
This is a good note, and PR submissions are very welcome.

But now the way to build the code is relatively backward, this is my problem, if you use `webworker`, please try to refer to the way of the parser, let the `webworker` code be injected into the built code. This is a troublesome thing, thank you again for your feedback.

**Comment by Naeemo** [comment]
OK, I'll try to provide a PR soon

**Comment by lijialiang** [comment]
We have accepted your PR and thank you very much for your contribution.
