### ISSUE TITLE
Sometimes need start animation without clear renderer

### ISSUE THREAD

**Issue by windyrain** [svga/SVGAPlayer-Web-Lite#23]
Hi, @lijialiang !

I encounter a problem like #10 . when I do `player.start()` after `player.pause()`.

After read source code, I found

https://github.com/svga/SVGAPlayer-Web-Lite/blob/master/core/player/index.ts#L114

This line will cause canvas flicker

can we design api like below

* add play params :  `play (clearRenderer: boolean )`
or
* add `resume` function

**Comment by lijialiang** [comment]
I think `resume` is a good suggestion. 👍🏼 Can you provide a PR? We need your help

**Comment by windyrain** [comment]
It's my pleasure，here is my PR: https://github.com/svga/SVGAPlayer-Web-Lite/pull/25

**Comment by lijialiang** [comment]
Sorry for the late reply, we have received your PR, thank you very much for your contribution.
