### ISSUE TITLE
1.5.0-beta.4:  ReferenceError: Can't find variable: OffscreenCanvas

### ISSUE THREAD

**Issue by hduwkk** [svga/SVGAPlayer-Web-Lite#28]
safari浏览器报错:  ReferenceError: Can't find variable: OffscreenCanvas

layer.container;this._ofsCanvas=OffscreenCanvas?new OffscreenCanvas(t.width,t.height):document.createElement("canvas");

**Comment by lijialiang** [comment]
请问是什么平台的 safari 具体版本？

**Comment by lijialiang** [comment]
正式版本 v1.5.0 已修复该问题。
