### ISSUE TITLE
ts 文件 部分枚举类型未导出

### ISSUE THREAD

**Issue by mrzhaichao** [svga/SVGAPlayer-Web-Lite#29]
enum FILL_MODE  枚举未导出，在使用该枚举类型是，导出的FILL_MODE 是个undefind,  需要本身声明这样一个枚举，建议完善一下代码

**Comment by Naeemo** [comment]
> enum FILL_MODE 枚举未导出，在使用该枚举类型是，导出的FILL_MODE 是个undefind, 需要本身声明这样一个枚举，建议完善一下代码

我临时fork了一个版本

yarn add svga-web
