### ISSUE TITLE
要如何导入扩展声音功能呢?

### ISSUE THREAD

**Issue by flbamao** [svga/SVGAPlayer-Web-Lite#34]
想给动画添加声音需要如何扩展呢？

**Comment by Naeemo** [comment]
> 想给动画添加声音需要如何扩展呢？

我临时fork了一个版本，支持了声音播放。

`yarn add svga-web`

**Comment by lijialiang** [comment]
lite 版本暂不支持声音播放，原因主要在于声音的播放在移动端浏览器兼容性不稳定性。

如果必须声音的支持，可以尝试使用 [SVGAPlayer-Web](https://github.com/svga/SVGAPlayer-Web) 版本
