### ISSUE TITLE
为啥不是 铺满canvas的状态

### ISSUE THREAD

**Issue by zhangyingjie123** [svga/SVGAPlayer-Web-Lite#38]

**Comment by lijialiang** [comment]
@zhangyingjie123 请问能否提供一个 demo ？我们能更好地排查问题情况。

**Comment by lijialiang** [comment]
canvas 画布的比例是不确定的，但动画的大小比例是确定的，所以不一定满足完全铺满画布空间。

当设置 canvas 比例等于动画大小比例一致时，完全可以铺满画布。
