### ISSUE TITLE
parser.do()方法在频繁创建parser时，会有无响应的情况。

### ISSUE THREAD

**Issue by superOnes** [svga/SVGAPlayer-Web-Lite#39]

**Comment by Naeemo** [comment]
`parser` 是可以复用的；不方便复用时，要及时`parser.destroy()` 。

**Comment by superOnes** [comment]
我的场景呢，就是要创建多个parser的，但是在频繁的过程中，发现有一些漏掉了，这个要怎么解决呢。

**Comment by Naeemo** [comment]
如果不能全局共享 `parser` 的话，我现在也没什么办法。
每个 `parser` 会创建一个 `worker`，我们遇到的情况是短时间频繁创建 `parser` 时，相应的 `worker` 反应明显有延迟，导致动画也跟着延迟播放。

**Comment by superOnes** [comment]
....
const parser = new Parser()
function play(fileData) {
    parser.do(fileData).then(svgaData => {
        console.log(svgaData)
        .....
    })
}
这个play方法呢，会频繁的多次调用，比如我调用paly方法4次，console打印次数可能就是3次，甚至2次

**Comment by Naeemo** [comment]
> ....
> const parser = new Parser()
> function play(fileData) {
> parser.do(fileData).then(svgaData => {
> console.log(svgaData)
> .....
> })
> }
> 这个play方法呢，会频繁的多次调用，比如我调用paly方法4次，console打印次数可能就是3次，甚至2次

看来和我的情况不一样，你可以考虑把 `parser.do()` 的结果存下来，或者用自带的缓存。

**Comment by superOnes** [comment]
问题就在于，这个时候，我拿不到.then之后的结果，没有回调，parser.do好像失败了

**Comment by Naeemo** [comment]
> 问题就在于，这个时候，我拿不到.then之后的结果，没有回调，parser.do好像失败了

.catch 有异常吗？

**Comment by superOnes** [comment]
也试过，捕获不到

**Comment by superOnes** [comment]
parse.do这个方法有判断svga是否被缓存吗，是不是有加载过，之后再就不响应了

**Comment by Naeemo** [comment]
> parse.do这个方法有判断svga是否被缓存吗，是不是有加载过，之后再就不响应了

没有

**Comment by lijialiang** [comment]
@superOnes 不应该在播放时才进行解析，解析 svga 文件本身是一个耗时耗性能的操作，并且浏览器不能无休止地新建 worker，这个操作也是一个昂贵的开销，尽可能前置这个操作并与下载做成队列。
