### ISSUE TITLE
vscode插件 svga perview

### ISSUE THREAD

**Issue by ETTTTT** [svga/SVGAPlayer-Web-Lite#41]
基于你这个轻量级的包，写了一个vscode插件，可以在vscode里面像看图片样看svga了，svga perview可以试试

**Comment by lijialiang** [comment]
十分感谢你的贡献，这是我们一直想做的事情，后续我们会附带这个插件的信息在 README 上，让更多开发者体验方便性。

**Comment by ETTTTT** [comment]
不客气
