### ISSUE TITLE
How to configure nginx? 如何在 nginx 中配置以支持 svga 远程调用？

### ISSUE THREAD

**Issue by fengcms** [svga/SVGAPlayer-Web-Lite#42]
我尝试远程调用演示站上的 svga 文件，是可以正常使用的。

但是，我尝试调用我们自己服务器上的 svga 文件，无法正常使用。

我觉得应该是我的 nginx 配置没有做好，所以想请问一下，在 nginx 上要如何配置，才能支持 svga 文件的远程调用。

---
I try to call the SVGA file on the demo station remotely, which can be used normally.

However, I tried to call the SVGA file on our own server and it didn't work properly.

I think it should be my nginx configuration is not done well, so I would like to ask how to configure it on nginx to support the remote call of SVGA files.

---
My English is not good, the above English content for Google translation.

thinks

**Comment by lijialiang** [comment]
可以理解为类似于 jpg、png 等图片资源即可。
