### ISSUE TITLE
android 6.0.1 指定svga播放出现 TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by janceChun** [svga/SVGAPlayer-Web-Lite#43]
svga: https://o-static.ihago.net/ikxd/e8357fa5cee5d79f2e4473fe12a4ce56/choujian.svga

![image](https://user-images.githubusercontent.com/4457572/130404940-2f1fee76-fd8c-4272-bf7b-ddaf027d737d.png)
![image](https://user-images.githubusercontent.com/4457572/130405208-52fc6bd5-14c4-48b4-9f63-cb3d4ce06df9.png)

**Comment by lijialiang** [comment]
这个链接的 svga 在测试用例上能被正常播放，请排查下 Player 是否传入的正确解析后的 svga 数据
