### ISSUE TITLE
SVGAPlayer-Web-Lite not work on ios 14.6 wkwebview

### ISSUE THREAD

**Issue by DavidQinqianWu** [svga/SVGAPlayer-Web-Lite#44]
i found that on ios 14.6 version ,the wkwebview not working with SVGAPlayer-web-lite, which cant load the SVGA animation(no errors, not warnings, just dont show up). but on ios 14.7 it works good and some versions (such as ios 13.x, not fully test). Any solutions or reasons?  thanks :)

**Comment by lijialiang** [comment]
Hi, we tested iOS version 14.6 on a real cloud machine and it works fine, can you please provide more information?

## TestLink
**[https://legoflow.com/assets/svga-lite/](https://legoflow.com/assets/svga-lite/)**


## TestScreenshot
![image](https://user-images.githubusercontent.com/12247242/132610002-5830465f-d943-47fb-b958-79b6b6768b6f.png)
