### ISSUE TITLE
如何捕获下载svga失败？

### ISSUE THREAD

**Issue by Jun90925** [svga/SVGAPlayer-Web-Lite#45]
在`parser.load`加载svga文件的时候，如果文件不存在，并没有错误事件，也不会进入`catch`。

**Comment by lijialiang** [comment]
@Jun90925 你好，请尝试新版本 [v2.0.3](https://www.npmjs.com/package/svga/v/2.0.3) 已修复该问题，附带一个 [测试例子](https://js-p1kuds.stackblitz.io)。

**Comment by Jun90925** [comment]
> @Jun90925 你好，请尝试新版本 [v2.0.3](https://www.npmjs.com/package/svga/v/2.0.3) 已修复该问题，附带一个 [测试例子](https://js-p1kuds.stackblitz.io)。

完美解决！
