### ISSUE TITLE
使用DB报错

### ISSUE THREAD

**Issue by qwerWSQ** [svga/SVGAPlayer-Web-Lite#48]
Cannot set properties of undefined (setting 'storeName')

**Comment by Naeemo** [comment]
could you please provide a minimal repro or some code?

**Comment by qwerWSQ** [comment]
> could you please provide a minimal repro or some code?

import { DB } from 'svga'

const db = DB()

**Comment by Naeemo** [comment]
try `new DB()`, I notice it's missing in the README

**Comment by qwerWSQ** [comment]
> try `new DB()`, I notice it's missing in the README

i write try then catch report error
error is Cannot set properties of undefined (setting 'storeName')

**Comment by Naeemo** [comment]
``` javascript
import { DB } from 'svga'

const db = new DB() // I mean add the missing 'new'
```

**Comment by qwerWSQ** [comment]
> ```js
> import { DB } from 'svga'
> 
> const db = new DB() // I mean add the missing 'new'
> ```
。。。。 It works. Thank You.

**Comment by Naeemo** [comment]
You're welcome. 😉

**Comment by Naeemo** [comment]
You may close this now.
