### ISSUE TITLE
图片剪裁不生效

### ISSUE THREAD

**Issue by dezhongzhang** [svga/SVGAPlayer-Web-Lite#51]
clipPath没有绘制，导致图片剪裁没有生效，SVGAPlayer-Web和web-lite的效果不一致

**Comment by lijialiang** [comment]
麻烦请提供一个 svga 文件链接

**Comment by dezhongzhang** [comment]
链接: https://pan.baidu.com/s/1AsYDPhZV-MYfdvIf-A18cw 
提取码: u79v

**Comment by lijialiang** [comment]
版本 [v2.0.5](https://www.npmjs.com/package/svga/v/2.0.5) 已修复

测试例子
[https://stackblitz.com/edit/web-platform-mhfojp?file=index.html](https://stackblitz.com/edit/web-platform-mhfojp?file=index.html)
