### ISSUE TITLE
调用start之前canvas是空白没有内容的，期望渲染第一帧

### ISSUE THREAD

**Issue by Skandar-Ln** [svga/SVGAPlayer-Web-Lite#52]
如何做到我start之前渲染出来第一帧，点击之后才start然后播放动画？

**Comment by lijialiang** [comment]
可以先配置只 start 出一帧，然后点击后重设配置进行渲染全部帧。

这里有一个 [example](https://stackblitz.com/edit/svelte-gi15rv?file=index.html)。
