### ISSUE TITLE
这个支持一个文件，多个动画吗？

### ISSUE THREAD

**Issue by df257** [svga/SVGAPlayer-Web-Lite#54]
比如，一个人，有待机，奔跑，死亡，多个动画，能全在一个文件里，然后播放时指定对应动画名字就行

**Comment by lijialiang** [comment]
对于现有 SVGA 格式来说是无法直接满足这个功能。只能根据不同动画的帧区间（例如 0 到 100 是奔跑、101 到 200 是死亡），然后指定区间去播放动画。
