### ISSUE TITLE
您好，请问这个svga文件缓存的方式有哪些，可以像css/js文件一样走浏览器缓存么，（目前已知的是indexDB,内存缓存videoItem）

### ISSUE THREAD

**Issue by apppleKey** [svga/SVGAPlayer-Web-Lite#55]

**Comment by apppleKey** [comment]
每次播放同一个svga都会发请求拉svga资源，我们的svga文件有好几兆，网速慢的话要等好久

**Comment by lijialiang** [comment]
从这个 [demo](https://output.jsbin.com/fukafip) 来说，服务器对静态资源有设置缓存的话，重复访问页面 chrome 浏览器自动会从本地缓存里面拿数据。

禁用缓存
![image](https://user-images.githubusercontent.com/12247242/148522108-bbcafc77-77b5-4b66-8af5-a90785b5e50c.png)




启用缓存
![image](https://user-images.githubusercontent.com/12247242/148522176-54ea6421-f1fb-497f-add7-68faf8f42918.png)
