### ISSUE TITLE
Uncaught SyntaxError: Private field '#PARSER_V2_INLINE_WROKER' must be declared in an enclosing class

### ISSUE THREAD

**Issue by changwaidaiji** [svga/SVGAPlayer-Web-Lite#56]
你好，想问下parser.ts里有两行代码
`const INLINE_WORKER_FLAG = '#PARSER_V2_INLINE_WROKER#'`
`this.worker = new Worker(window.URL.createObjectURL(new Blob([INLINE_WORKER_FLAG])))`
我这边在自己项目里跑了下会报Uncaught SyntaxError: Private field '#PARSER_V2_INLINE_WROKER' must be declared in an enclosing class这个错误，想问下初始化worker时传这个进去是为什么

**Comment by lijialiang** [comment]
PARSER_V2_INLINE_WROKER 字段是作为标识位，把 Parser 编译后的代码转为字符串插值进去，这样的做法有两个原因：

1. 通过 `new Worker(window.URL.createObjectURL(new Blob()))` 可以把 Parser 以 worker 新建后台线程执行一些解析计算等相对影响性能的功能
2. 对于不支持 worker 的浏览器也可降级，通过配置 `isDisableWebWorker = false` 方式取消 Parser 使用 worker，改用 eval 方式在主线程完成相关功能
