### ISSUE TITLE
use TS to code with SVGALITE，error with  declare OffscreenCanvas 

### ISSUE THREAD

**Issue by sxc20181120** [svga/SVGAPlayer-Web-Lite#61]
when i use ts to build my file,it will show a error about t declare type ReplaceElement ,it says "Cannot find name 'OffscreenCanvas'",is that bug has realtion with ts's version

**Comment by lijialiang** [comment]
The use of `OffscreenCanvas` on TS requires configuration on tsconfig.json, e.g. like this

```
{
  "compilerOptions": {
    "types": [
      "node",
      "offscreencanvas"
    ]
  }
}
```

**Comment by Chance722** [comment]
yarn add @types/offscreencanvas -D by yourself.
