### ISSUE TITLE
绘制图形时，缺失描边

### ISSUE THREAD

**Issue by flying19880517** [svga/SVGAPlayer-Web-Lite#64]
fill和stoke都可以有，现在多了个else，会跳过描边

```JavaScript
  if (styles.fill !== null) {
    context.fill()
  } else if (styles.stroke !== null) {
    context.stroke()
  }
```

https://github.com/svga/SVGAPlayer-Web-Lite/blob/f7f732789d06da7d74c06adf89e091e68f2a8e78/src/player/render.ts#L188

**Comment by Naeemo** [comment]
@flying19880517 
有可复现的 URL 和截图吗？

**Comment by flying19880517** [comment]
> @flying19880517 有可复现的 URL 和截图吗？

<img width="382" alt="image" src="https://user-images.githubusercontent.com/344444/175289386-30f66cb4-d296-40db-9c5c-bb3b6252aa54.png">
