### ISSUE TITLE
加载SVGA资源时候，出现跨域的错误

### ISSUE THREAD

**Issue by YupongUU** [svga/SVGAPlayer-Web-Lite#67]
在加载 svga文件的时候，如果资源的链接和当前页面不同源，就会报跨域的错误。这个有什么方法解决吗？

**Comment by Naeemo** [comment]
> 在加载 svga文件的时候，如果资源的链接和当前页面不同源，就会报跨域的错误。这个有什么方法解决吗？

这应该与svga无关。去了解一下CORS就知道该怎么解决了。😊
