### ISSUE TITLE
文字替换后乱码崩坏

### ISSUE THREAD

**Issue by fuck-all-mistakes** [svga/SVGAPlayer-Web-Lite#73]
![屏幕截图 2022-12-10 161055](https://user-images.githubusercontent.com/81461519/206840483-8627a018-b5af-4afe-b0c3-f7c47b1f74b3.png)
![屏幕截图 2022-12-10 161012](https://user-images.githubusercontent.com/81461519/206840486-f0b51a04-7777-4637-9e59-1e3c143b0e70.png)
![屏幕截图 2022-12-10 160856](https://user-images.githubusercontent.com/81461519/206840489-6df3be50-2bf4-4caa-92f9-5d93978b528a.png)
![屏幕截图 2022-12-10 160826](https://user-images.githubusercontent.com/81461519/206840498-bd386aff-34ec-4dd3-99f8-7d71f6c6d8e4.png)
![屏幕截图 2022-12-10 160800](https://user-images.githubusercontent.com/81461519/206840513-88ad5b07-d210-423f-abca-88fda96b61aa.png)

**Comment by lijialiang** [comment]
目前 lite 版本只会把传入的动态节点 canvas 作为元素图进行绘制，没有调整修改动态节点的内容，能否提供一个可重现问题的 demo，方便排查修复。
