### ISSUE TITLE
火狐浏览器中  动画没有清除前一帧的画面

### ISSUE THREAD

**Issue by stupppid** [svga/SVGAPlayer-Web-Lite#76]
我注意到  /src/player/index.ts  中有一个 clearContainer 方法，是通过修改宽度来清除画布，在火狐上不清楚为什么并没有生效。

**Comment by lijialiang** [comment]
目前排查到是因为 Firefox 浏览器对 OffscreenCanvas 没有清理历史画布内容导致的，因此尝试每次绘制前重新实例化 OffscreenCanvas，从而避免原有历史画布内容。

版本：2.0.8-alpha.1

**Comment by stupppid** [comment]
OK了，谢谢大佬
