### ISSUE TITLE
isOpenNoExecutionDelay开关

### ISSUE THREAD

**Issue by zengrc** [svga/SVGAPlayer-Web-Lite#77]
isOpenNoExecutionDelay为true的时候，利用woker回调模拟动画刷新，但worker中的setTimeout间隔是1/60，是否是1000/60，60分之一毫秒相当于马上执行了吧

`'onmessage = function () {setTimeout(function() {postMessage(null)}, 1 / 60)}'`

**Comment by lijialiang** [comment]
是的，我们 review 疏忽，已提交修复版本 2.1.1
