### ISSUE TITLE
does not support edge browser

### ISSUE THREAD

**Issue by zsytssk** [svga/SVGAPlayer-Web-Lite#9]
IE 11, chrome firefox support but not edge browser; show error belog:
<img width="900" alt="WX20200617-101910@2x" src="https://user-images.githubusercontent.com/2304648/84847678-3afc3400-b084-11ea-9257-e498c30e1ebd.png">

**Comment by lijialiang** [comment]
We tried to run testcases on Edge, but failed to reproduce the problem, please provide more detailed environmental information. @zsytssk 

![image](https://user-images.githubusercontent.com/12247242/84851644-6f282280-b08d-11ea-8b2f-95b7df20da39.png)

**Comment by zsytssk** [comment]
@lijialiang 
[归档.zip](https://github.com/svga/SVGAPlayer-Web-Lite/files/4796728/default.zip)
you can download this demo and open with local server in edge will find error。。

**Comment by zsytssk** [comment]
@lijialiang 
[归档.zip](https://github.com/svga/SVGAPlayer-Web-Lite/files/4796771/default.zip)
open file in local server you will find error, maybe some effect cause this error;
![WX20200618-145457](https://user-images.githubusercontent.com/2304648/84988222-344cea00-b174-11ea-9e10-9c1c4103cc46.png)

**Comment by lijialiang** [comment]
@zsytssk 

After testing, this problem came from the fact that when the parser used the webworker to decompress data, the edge failed to provide enough memory space. 

So you can try to disable the replacement webworker thread.

```js
const ua = navigator.userAgent
const parser = new SVGA.Parser({
  disableWorker: ua.indexOf('Edge')
})
```

**Comment by zsytssk** [comment]
@lijialiang  thk 谢谢
